
[[dependencies]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[dependencies]]
  branch = "master"
  name = "github.com/pkgutil/osutil"

[[dependencies]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/cli"

[[dependencies]]
  branch = "master"
  name = "github.com/zchee/go-xdgbasedir"
